Repository proxystore/taps, pull requests merged in 2024-06, with the labels that each got.

#67 Update README and release guide
  README.md
  docs/contributing/releases.md
Labels: documentation

#68 Fix publish workflow and release template
  .github/release.yml
  .github/workflows/publish.yml
Labels: package

#69 Bump to TaPS v0.2.0a1
  pyproject.toml
Labels: package

#70 Update LICENSE authors
  LICENSE
Labels: package

#72 Add figures and tables to docs
  docs/apps/index.md
  docs/static/app-structures.svg
  docs/static/framework-stack.svg
  taps/__init__.py
Labels: documentation

#77 Rename `DAGExecutor` to `FutureDependencyExecutor`
  taps/executor/__init__.py
  taps/executor/globus.py
  taps/executor/python.py
  taps/executor/utils.py
  testing/fixtures.py
  tests/engine/engine_test.py
  tests/executor/python_test.py
  tests/executor/utils_test.py
Labels: breaking

#81 Fix exception logging in task callback
  taps/engine/engine.py
  tests/engine/engine_test.py
Labels: bug

#80 Add failure injection app
  docs/apps/failures.md
  docs/apps/index.md
  mkdocs.yml
  pyproject.toml
  taps/apps/configs/failures.py
  taps/apps/failures/__init__.py
  taps/apps/failures/app.py
  taps/apps/failures/types.py
Labels: enhancement
