Repository proxystore/taps, pull requests merged in 2024-05, with the labels that each got.

#4 Improve configuration and fix CI
  README.md
  pyproject.toml
  testing/fixtures.py
  testing/globus.py
  testing/workflow.py
  tests/config_test.py
  tests/conftest.py
  tests/context_test.py
  tests/executor/__init__.py
  tests/executor/config_test.py
  tests/executor/globus_test.py
  tests/logging_test.py
  tests/run/__init__.py
  tests/run/__init__.pyq
  tests/run/config_test.py
  tests/run/main_test.py
  wbench/config/benchmark.py
  wbench/run.py
  wbench/utils.py
  wbench/wf/template.py
  wbench/workflow.py
  webs/__init__.py
  webs/config.py
  webs/context.py
  webs/executor/__init__.py
  webs/executor/config.py
  webs/executor/globus.py
  webs/executor/python.py
  webs/logging.py
  webs/py.typed
  webs/run/__main__.py
  webs/run/config.py
  webs/run/main.py
  webs/wf/__init__.py
  webs/workflow.py
Labels: breaking

#5 Add documentation site
  .github/workflows/check-docs.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  README.md
  docs/_overrides/base.html
  docs/_templates/python/material/docstring/admonition.html
  docs/_templates/python/material/function.html
  docs/_templates/python/material/module.html
  docs/contributing/index.md
  docs/contributing/issues-pull-requests.md
  docs/contributing/releases.md
  docs/contributing/style-guide.md
  docs/css/extra.css
  docs/css/mkdocstrings.css
  docs/generate_api.py
  docs/get-started.md
  docs/guides/creating-workflows.md
  docs/guides/index.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
  tox.ini
  webs/logging.py
  webs/run/__init__.py
Labels: documentation

#6 Add DAG Executor wrapper
  testing/fixtures.py
  tests/conftest.py
  tests/executor/dag_test.py
  webs/executor/dag.py
Labels: enhancement

#7 Add `WorkflowExecutor`
  testing/fixtures.py
  testing/workflow.py
  tests/conftest.py
  tests/executor/workflow_test.py
  tests/run/__init__.pyq
  webs/executor/workflow.py
  webs/run/main.py
  webs/workflow.py
Labels: breaking

#8 Add simple synthetic benchmark
  testing/fixtures.py
  testing/workflow.py
  tests/data_test.py
  tests/executor/workflow_test.py
  tests/wf/__init__.py
  tests/wf/synthetic/__init__.py
  tests/wf/synthetic/workflow_test.py
  webs/data.py
  webs/executor/python.py
  webs/executor/workflow.py
  webs/run/main.py
  webs/wf/__init__.py
  webs/wf/synthetic/__init__.py
  webs/wf/synthetic/config.py
  webs/wf/synthetic/workflow.py
  webs/workflow.py
Labels: breaking

#9 Add `ProcessPoolExecutor` support
  tests/executor/python_test.py
  webs/executor/python.py
Labels: enhancement

#11 Refactor `WorkflowExecutor` and improve logging
  .pre-commit-config.yaml
  pyproject.toml
  testing/fixtures.py
  testing/record.py
  testing/workflow.py
  tests/executor/workflow_test.py
  tests/record_test.py
  webs/executor/workflow.py
  webs/record.py
  webs/run/config.py
  webs/run/main.py
  webs/wf/synthetic/workflow.py
Labels: breaking

#27 Add `as_completed` and `wait` for `TaskFuture`
  testing/fixtures.py
  tests/conftest.py
  tests/executor/workflow_test.py
  webs/executor/dask.py
  webs/executor/workflow.py
Labels: enhancement

#28 Federated Learning workflow implementation
  .gitignore
  pyproject.toml
  webs/wf/__init__.py
  webs/wf/fedlearn/__init__.py
  webs/wf/fedlearn/config.py
  webs/wf/fedlearn/modules.py
  webs/wf/fedlearn/tasks.py
  webs/wf/fedlearn/types.py
  webs/wf/fedlearn/utils.py
  webs/wf/fedlearn/workflow.py
Labels: enhancement

#29 Added Montage workflow
  pyproject.toml
  webs/wf/__init__.py
  webs/wf/montage/__init__.py
  webs/wf/montage/config.py
  webs/wf/montage/workflow.py
Labels: enhancement

#30 Assorted usability improvements
  tests/executor/workflow_test.py
  webs/executor/workflow.py
  webs/run/main.py
  webs/wf/mapreduce/config.py
  webs/wf/mapreduce/utils.py
  webs/wf/mapreduce/workflow.py
Labels: enhancement

#31 Add Docking workflow implementation
  pyproject.toml
  webs/wf/__init__.py
  webs/wf/docking/__init__.py
  webs/wf/docking/config.py
  webs/wf/docking/train.py
  webs/wf/docking/workflow.py
Labels: enhancement

#37 Add the `moldesign` application and refactor app registration system
  .gitignore
  docs/guides/creating-workflows.md
  pyproject.toml
  testing/fixtures.py
  testing/workflow.py
  tests/executor/workflow_test.py
  tests/run/main_test.py
  tests/workflow_test.py
  tox.ini
  webs/executor/workflow.py
  webs/run/main.py
  webs/wf/__init__.py
  webs/wf/cholesky/__init__.py
  webs/wf/cholesky/workflow.py
  webs/wf/docking/__init__.py
  webs/wf/docking/workflow.py
  webs/wf/fedlearn/__init__.py
  webs/wf/fedlearn/workflow.py
  webs/wf/mapreduce/__init__.py
  webs/wf/mapreduce/workflow.py
  webs/wf/moldesign/__init__.py
  webs/wf/moldesign/chemfunctions.py
  webs/wf/moldesign/config.py
  webs/wf/moldesign/tasks.py
  webs/wf/moldesign/workflow.py
  webs/wf/montage/__init__.py
  webs/wf/montage/workflow.py
  webs/wf/synthetic/__init__.py
  webs/wf/synthetic/workflow.py
  webs/workflow.py
Labels: breaking

#40 Expand synthetic workflow
  tests/wf/synthetic/workflow_test.py
  webs/wf/synthetic/__init__.py
  webs/wf/synthetic/config.py
  webs/wf/synthetic/workflow.py
Labels: enhancement

#45 Add data transformers to CLI
  .gitignore
  pyproject.toml
  testing/fixtures.py
  tests/data/config_test.py
  tests/data/file_test.py
  tests/data/proxy_test.py
  tests/data/transform_test.py
  tests/executor/workflow_test.py
  tests/wf/synthetic/workflow_test.py
  webs/data/__init__.py
  webs/data/config.py
  webs/data/file.py
  webs/data/null.py
  webs/data/proxy.py
  webs/data/transform.py
  webs/executor/config.py
  webs/executor/workflow.py
  webs/run/config.py
  webs/run/main.py
  webs/wf/synthetic/workflow.py
Labels: breaking

#46 Remove upper bound on task times in tests
  tests/wf/synthetic/workflow_test.py
Labels: internal

#47 Change GitHub URL to taps
  README.md
  docs/contributing/index.md
  docs/contributing/issues-pull-requests.md
  docs/contributing/releases.md
  docs/get-started.md
  mkdocs.yml
  pyproject.toml
Labels: package

#48 Only wrap functions once in `WorkflowExecutor` and fix Globus Compute
  tests/executor/workflow_test.py
  webs/executor/globus.py
  webs/executor/workflow.py
Labels: enhancement

#49 Partially revert changes in #48
  tests/executor/workflow_test.py
  webs/executor/workflow.py
Labels: bug

#51 Add missing step in workflow
  webs/wf/montage/__init__.py
  webs/wf/montage/workflow.py
Labels: bug

#56 Triage minor errors from paper evaluation
  pyproject.toml
  tests/data/proxy_test.py
  tests/executor/globus_test.py
  tests/wf/synthetic/workflow_test.py
  webs/data/proxy.py
  webs/executor/dask.py
  webs/executor/globus.py
  webs/executor/python.py
  webs/executor/workflow.py
  webs/run/config.py
  webs/wf/docking/__init__.py
  webs/wf/docking/config.py
  webs/wf/docking/workflow.py
  webs/wf/moldesign/__init__.py
  webs/wf/moldesign/tasks.py
  webs/wf/montage/workflow.py
  webs/wf/synthetic/config.py
  webs/wf/synthetic/workflow.py
Labels: breaking, bug, documentation

#60 Add `close()` to `DataTransformer`
  taps/data/file.py
  taps/data/null.py
  taps/data/proxy.py
  taps/data/transform.py
  taps/engine/engine.py
  taps/engine/transform.py
  taps/run/apps/fedlearn.py
  taps/run/apps/synthetic.py
  taps/run/main.py
  tests/data/file_test.py
  tests/data/null_test.py
  tests/data/proxy_test.py
  tests/engine/transform_test.py
Labels: enhancement

#61 Add `{executor}` option to run dir
  taps/run/config.py
  taps/run/main.py
  testing/fixtures.py
Labels: enhancement

#62 Fix ProxyStore serialization issue with Ray
  pyproject.toml
  taps/apps/synthetic.py
  taps/context.py
  taps/engine/engine.py
  taps/executor/ray.py
  testing/fixtures.py
  tests/apps/synthetic_test.py
  tests/conftest.py
  tests/context_test.py
  tests/engine/proxy_test.py
  tox.ini
Labels: bug
