Repository proxystore/taps, pull requests merged in 2024-08, with the labels that each got.

#111 Ensure `run_dir` is an absolute path
  taps/run/config.py
Labels: bug

#113 Fix Dask `Future`s getting proxied in chained tasks
  taps/engine/__init__.py
  taps/engine/_engine.py
  taps/engine/_protocols.py
  taps/engine/_transform.py
  taps/executor/dask.py
  tests/engine/engine_test.py
Labels: bug

#114 Log failed tasks in moldesign when resubmitting
  taps/apps/moldesign/app.py
Labels: bug

#115 Refactor `taps.engine` module layout
  taps/engine/__init__.py
  taps/engine/_config.py
  taps/engine/_engine.py
  taps/engine/future.py
  taps/engine/task.py
  taps/engine/transform.py
  testing/fixtures.py
  tests/apps/cholesky_test.py
  tests/apps/failures/app_test.py
  tests/apps/mapreduce_test.py
  tests/apps/montage_test.py
  tests/apps/synthetic_test.py
  tests/conftest.py
  tests/engine/engine_test.py
  tests/engine/future_test.py
  tests/engine/task_test.py
  tests/engine/transform_test.py
Labels: internal

#116 Fix typo in CLI argument for Cholesky example
  docs/apps/cholesky.md
Labels: documentation

#117 Add FAQ and update Github templates and contributing guide
  .github/ISSUE_TEMPLATE/01_bug.yml
  .github/ISSUE_TEMPLATE/02_feature.yml
  .github/ISSUE_TEMPLATE/03_docs.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  .github/release.yml
  docs/contributing/index.md
  docs/contributing/issues-pull-requests.md
  docs/contributing/style-guide.md
  docs/faq.md
  mkdocs.yml
Labels: development, documentation

#118 Add `manager_selector` to Parsl HTEx config
  taps/executor/parsl.py
  tests/executor/parsl_test.py
Labels: enhancement

#125 Record total virtual memory instead of available
  taps/run/env.py
Labels: bug

#128 Use non-deprecated Parsl provider for tests
  tests/executor/parsl_test.py
Labels: internal

#129 Add TaPS preprint citation
  README.md
  docs/publications/index.md
  mkdocs.yml
Labels: documentation

#136 Upgrade doc dependencies and templates
  docs/_overrides/base.html
  docs/_templates/python/material/docstring/admonition.html
  docs/_templates/python/material/function.html
  docs/_templates/python/material/module.html
  docs/css/mkdocstrings.css
  docs/templates/python/material/module.html.jinja
  mkdocs.yml
  pyproject.toml
Labels: documentation, package

#137 Create `Config` docstrings from `Field` descriptions
  docs/guides/apps.md
  docs/guides/executor.md
  mkdocs.yml
  pyproject.toml
  taps/apps/configs/cholesky.py
  taps/apps/configs/docking.py
  taps/apps/configs/failures.py
  taps/apps/configs/fedlearn.py
  taps/apps/configs/mapreduce.py
  taps/apps/configs/moldesign.py
  taps/apps/configs/montage.py
  taps/apps/configs/synthetic.py
  taps/apps/fedlearn/types.py
  taps/apps/synthetic.py
  taps/engine/_config.py
  taps/engine/_engine.py
  taps/engine/task.py
  taps/executor/_protocol.py
  taps/executor/dask.py
  taps/executor/globus.py
  taps/executor/parsl.py
  taps/executor/python.py
  taps/executor/ray.py
  taps/filter/_object.py
  taps/filter/_protocol.py
  taps/filter/_simple.py
  taps/logging.py
  taps/run/config.py
  taps/run/parse.py
  taps/transformer/_file.py
  taps/transformer/_null.py
  taps/transformer/_protocol.py
  taps/transformer/_proxy.py
  tests/apps/configs/fedlearn_test.py
  tests/apps/configs/synthetic_test.py
  tests/engine/engine_test.py
Labels: documentation, internal

#138 Update logo, icon, and color palette
  docs/css/extra.css
  docs/static/favicon.png
  docs/static/icon-white.svg
  mkdocs.yml
Labels: documentation
